platform:
  - x64

configuration:
  - Debug
  - Release

image:
  - Visual Studio 2019

skip_commits:
  files:
    - README.md
    - LICENSE
    - CODE_OF_CONDUCT.md
    - CHANGELOG.md
    - .gitignore
    - .github/*
    - '**/*.html'

environment:
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: '-t7z -m0=lzma -mx=9'
  matrix:
    - TOOLSET: v142
#    - TOOLSET: ClangCL

cache:
  - c:\.conan -> conanfile.txt

clone_folder: c:/playlunky/

install:
  - git submodule update --init --recursive

before_build:
- cmd: python --version
- cmd: pip install conan --upgrade
- cmd: pip install numpy
- cmd: conan user
- cmd: conan --version
- ps: >-
    $ENV:PATH="$ENV:PATH;C:\Users\appveyor\AppData\Roaming\Python\Scripts"

    mkdir build

    cd build
- cmd: cmake c:/playlunky/ -G"Visual Studio 16 2019" -A x64 -T %TOOLSET%

build_script:
- cmake --build . --config %CONFIGURATION%

#test_script:
#- ctest -C %CONFIGURATION% --output-on-failure
